steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build and tag
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/product-listing-api:$TAG_NAME','.']
- name: 'gcr.io/cloud-builders/docker'
  id: Push image
  args: ['push', 'gcr.io/$PROJECT_ID/product-listing-api:$TAG_NAME']